# engine_base.yaml
# =============================================================================
# ENGINE BASE CONFIG — identification, geometry, materials, coarse hydraulics
# This file holds *plant* facts a user can read off nameplates/drawings/manuals.
# Loader must convert to SI internally according to the `units` section below.
# =============================================================================

units:
  # Allowed: m, mm ;  m2 ; m3 ; kg ; s, min ; C ; m3/h, kg/s ; W/K ; J/K
  length: m
  time: s
  temperature: C
  flow: m3/h            # if set to kg/s, keep rho_w consistent below
  area: m2
  mass: kg
  UA: W/K
  heat_capacity: J/K

engine:
  id: "Hyundai-MAN 6L70MC-C8"     # Free text identifier (for logs/reports).
  n_cyl: 6                        # [–] Number of cylinders (nameplate/Project Guide).
  bore: 0.70                      # [m] Liner *inner* diameter (bore).
  stroke: 2.36                    # [m] For reference/cross-checks.
  jcw_pump_nominal: 165.0         # [m3/h] JCW pump capacity at 100% (List of capacities).
  water_inside_engine: 634.0      # [kg] Mass of water *inside engine* only (table/spec).
  design_T_in: 66.0               # [°C] Typical inlet to engine (if known; optional).
  design_T_out: 80.0              # [°C] Typical outlet from engine (optional).

water_props:
  rho_w: 1000.0                   # [kg/m3] Use 980–1000 @ ~80 °C. Controls flow→mass conversion.
  cp_w: 4180.0                    # [J/(kg·K)] Specific heat of water.

elements:
  # Each element can be disabled (enabled: false). If geometry is unknown, set
  # area_override to a best estimate and leave di/do/height empty.
  liner:
    enabled: true
    material: "alloyed_cast_iron" # Match keys in your materials library.
    height: 0.46                  # [m] Wet height between O-rings (measured).
    di: 0.70                      # [m] Inner dia (bore).
    do: 0.95                      # [m] Outer dia where the jacket flows (measured).
    wall_thickness_override: null # [m] If known precisely; else derived from di/do.
    area_override: null           # [m2] If set, geometry above is ignored.
  head:
    enabled: true
    material: "forged_steel"
    height: 0.46                  # [m] Effective wet height (your convention).
    di: 0.70
    do: 1.00
    wall_thickness_override: null
    area_override: null
  valve_assembly:
    enabled: true
    material: "mixed_valve"
    # After the head, a part of the flow goes through this branch.
    phi_valve: 0.20               # [–] Mass fraction to valve branch (0…1). Tune if needed.
    # If geometry unknown, set area_override (typical starting guess ~1.0 m2 per engine).
    height: null
    di: null
    do: null
    wall_thickness_override: null
    area_override: 1.0

notes:
  - "Where to look: Project Guide (geometry), List of capacities (pump), ER logs (temperatures)."
  - "Bore is the *inner* diameter; heat transfer area uses an effective wet diameter between di and do."
  - "Include head and valve branch — they contribute area and metal heat capacity (often missing in quick models)."

model_options:
  h_correlation: "Dittus-Boelter"   # or "Gnielinski"
  d_eff_rule: "mid_di_do"           # "mid_di_do" | "explicit"
  d_eff_explicit: null              # [m] set if d_eff_rule=="explicit"
  fouling_factor: 0.90              # 0..1 multiplier on UA/K to account fouling
  K_scaling:
    enabled: true
    m_dot_ref_m3h: 165.0            # reference volumetric flow at 100%
    alpha: 0.70                      # K ∝ (m_dot/m_ref)^alpha

materials_library:                  # you can omit this if using hardcoded library in code
  alloyed_cast_iron:
    rho: 7200.0                     # kg/m3
    cp: 500.0                       # J/kg/K
    k: 35.0                         # W/m/K
  forged_steel:
    rho: 7850.0
    cp: 500.0
    k: 45.0
  mixed_valve:                      # averaged seat+body
    rho: 7700.0
    cp: 480.0
    k: 40.0

cm_method:
  mode: "penetration_depth"         # "half_wall" | "penetration_depth" | "override"
  tau_w_s: 10.0                     # time scale for thermal penetration (if mode=="penetration_depth")
  cm_override_J_per_K: null         # use if mode=="override" (per element can also override)

engine_internal:
  transport_delay_s: 10.0           # for PFR integration (engine inlet→heat zone)

qjw_model:
  mode: "scaled"                    # "scaled" | "table"
  qjw_100pct_kW: 1200.0             # nominal jacket-water heat at 100% load
  scale_wrt: "rpm"                  # "bhp" | "rpm" | "bhp_rpm_combo"
  table: []                         # if mode=="table": [{rpm:…, bhp:…, qjw_kW:…}, …]

calibration_overrides:
  K_factor_global: 1.00             # post-multiplicative factor on all K’s
  liner:
    K_override_W_per_K: null
    Cm_override_J_per_K: null
  head:
    K_override_W_per_K: null
    Cm_override_J_per_K: null
  valve_assembly:
    K_override_W_per_K: null
    Cm_override_J_per_K: null